name: SimpleAnnouncer
main: me.xxben.simpleannouncer.SimpleAnnouncer
author: xxBen
description: "Announcements Made Simple"
version: 1.0

commands:
  announcer:
    description: Main Command
    aliases: [sannouncer, simpleannouncer]